openapi: 3.0.3
info:
  title: Account-manager WhiteBoard
  description: Componente responsável por criar e gerenciar contas.
  version: 0.0.1
host: localhost
basePatch: /v1
tags:
  - name: Conta
    description: Operações do usuário
  - name: Validação
    description: Permissões de acesso
schemes:
  - http
paths:
  /new/user:
    post:
      tags:
        - Conta
      summary: Cria uma nova conta
      description: Gera uma nova conta no site.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccountRequestPresentation'
        required: true
      responses:
        '200':
          description: Cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAccountResponsePresentation'
        '400':
          description: Dados de cadastros inválidos
        '500':
          description: Ocorreu um erro interno
        '503':
          description: Service Unavailable
components:
  schemas:
    Endereco:
      type: object
      properties:
        rua:
          type: string
          example: "437 Lytton"
        cidade:
          type: string
          example: "Palo Alto"
        estado:
          type: string
          example: "MG"
        cep:
          type: string
          example: '94301'
    NewAccountRequestPresentation:
      type: object
      properties:
        nome:
          type: string
          example: "Gabriel"
        cpf:
          type: string
          format: int64
          example: "00000000000"
        email:
          type: string
          example: "teste@gmail.com"
        endereco:
          $ref: '#/components/schemas/Endereco'
        dataNascimento:
          type: string
          format: date
    NewAccountResponsePresentation:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 0
        nome:
          type: string
          example: "Gabriel"
        cpf:
          type: string
          example: "00000000000"
        email:
          type: string
          example: "teste@gmail.com"
        endereco:
          $ref: '#/components/schemas/Endereco'
        dataNascimento:
          type: string
          format: date
        dataInclusao:
          type: string
          exemple: "2023-01-15T02:47:00Z"
        status:
          type: string
          description: Como se encontra a conta A | B | F
          example: A
